{{- range .Values.persistentVolumeClaims -}}
{{- if not .claimName -}}
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
{{- if .annotations }}
  annotations:
{{- toYaml .annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
  name: {{ include "generic-app.name" $ }}-{{ .name }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .size }}"
{{/*
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" $ | nindent 6 }}
*/}}
{{- end -}}
{{- end -}}
