# Default values for generic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

# Environment variables
env: []
  # - name: VAR1
  #   value: "VAL1"

livenessProbe:
  enabled: false
  # httpGet:
  #   scheme: HTTP | HTTPS
  #   path: /
  #   port: http
  # exec:
  #   command:
  # tcpSocket:
  #   port: http
  # failureThreshold: 3
  # periodSeconds: 10

readinessProbe:
  enabled: false
  # httpGet:
  #   scheme: HTTP | HTTPS
  #   path: /
  #   port: http
  # exec:
  #   command:
  # tcpSocket:
  #   port: http
  # failureThreshold: 3
  # periodSeconds: 10

startupProbe:
  enabled: false
  # httpGet:
  #   scheme: HTTP | HTTPS
  #   path: /
  #   port: http
  # exec:
  #   command:
  # tcpSocket:
  #   port: http
  # failureThreshold: 3
  # periodSeconds: 10

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
initContainers: []

service:
  type: ClusterIP
  ports: []
    # - name: http
    #   targetPort: http
    #   protocol: TCP
    #   port: 80
    #   nodePort: 31000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: null
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

hostNetwork: false

nodeSelector: {}

tolerations: []

affinity: {}